---
- name: Install Supervisord
  hosts: localhost
  gather_facts: no
  become: yes
  tasks:

    - name: Ensure EPEL repository is installed
      dnf:
        name: epel-release
        state: present

    - name: Install Supervisor
      dnf:
        name: supervisor
        state: present

    - name: updating configuration supervisord.conf
      copy:
        dest: "/etc/supervisord.conf"
        content: |
          [supervisord]
          logfile=/twid/tasks/storage/logs/supervisord.log ; (main log file;default $CWD/supervisord.log)
          logfile_maxbytes=50MB        ; (max main logfile bytes b4 rotation;default 50MB)
          logfile_backups=10           ; (num of main logfile rotation backups;default 10)
          loglevel=info                ; (log level;default info; others: debug,warn,trace)
          pidfile=/tmp/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
          nodaemon=false               ; (start in foreground if true;default false)
          minfds=1024                  ; (min. avail startup file descriptors;default 1024)
          minprocs=200                 ; (min. avail process descriptors;default 200)
          ;umask=022                   ; (process file creation umask;default 022)
          user=kushal                  ; (default is current user, required if root)
          ;identifier=supervisor       ; (supervisord identifier, default is 'supervisor')
          directory=/tmp               ; (default is not to cd during start)
          ;nocleanup=true              ; (don't clean up tempfiles at start;default false)
          ;childlogdir=/tmp            ; ('AUTO' child log dir, default $TEMP)
          ;environment=KEY="value"     ; (key value pairs to add to environment)
          ;strip_ansi=false            ; (strip ansi escape codes in logs; def. false)
          
          [rpcinterface:supervisor]
          supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
          
          [unix_http_server]
          file=/tmp/supervisor.sock
          chmod=0755 ; sockef file mode (default 0700)
          
          [inet_http_server]
          port=127.0.0.1:9005
          ;username=abc
          
          [supervisorctl]
          ;srevreurl=http://127.0.0.1:9001
          serverurl=unix:///tmp/supervisor.sock
          ;username=abc
          ;serverurl=unix:///var/run/supervisor.sock ; use a unix:// URL  for a unix socket
          
          [include]
          files = /etc/supervisord.d/*.conf
         
    - name: updating configuration supervisord config
      copy:
        dest: "/etc/supervisord.d/laravel-worker.conf"
        content: |
          [program:laravel-worker-11]
          process_name=%(program_name)s_%(process_num)02d
          command=php /twid/tasks/artisan queue:work redis_queue --queue=cug --sleep=0 --tries=3 --max-jobs=100 --max-time=200
          autostart=true
          autorestart=true
          user=kushal
          numprocs=5
          redirect_stderr=true
          stdout_logfile=/twid/tasks/storage/logs/redis_cug.log
