---
- name: Install Composer
  hosts: localhost
  gather_facts: no
  become: true
  tasks:
    - name: Download Composer installer to /tmp
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-setup.php

    - name: Install Composer
      shell: |
        cd /tmp
        php composer-setup.php
      args:
        creates: /usr/local/bin/composer  # Skip if Composer is already installed

    - name: Move Composer to /usr/local/bin
      command:
        cmd: mv /tmp/composer.phar /usr/local/bin/composer
#       creates: /usr/local/bin/composer  # Skip if Composer is already installed

    - name: Clean up Composer installer
      file:
        path: /tmp/composer-setup.php
        state: absent

    - name: Install redis extension via PECL
      command: pecl install redis
#      creates: /usr/lib/php/modules/redis.so

    - name: Install APCu extension via PECL
      command: pecl install apcu
#      creates: /usr/lib/php/modules/apcu.so
