---
- name: Install and Configure Logwatch with Postfix
  hosts: localhost
  gather_facts: no
  become: yes
  tasks:

    - name: Install EPEL repository
      dnf:
        name: epel-release
        state: present

    - name: Install Logwatch package
      dnf:
        name: logwatch
        state: present

    - name: Install Postfix package
      dnf:
        name: postfix
        state: present

    - name: Enable and start Postfix service
      systemd:
        name: postfix
        state: started
        enabled: yes

    - name: Ensure Logwatch is configured for Postfix
      lineinfile:
        path: /etc/logwatch/conf/services/postfix.conf
        create: yes
        line: "*.log"
        state: present
