---
- name: update php-fpm config file
  hosts: localhost
  gather_facts: no
  become: true

  tasks:
    - name: updating configuration php.ini
      copy:
        dest: "/etc/php.ini"
        content: |
          [PHP]
          

    - name: updating configuration php-fpm config
      copy:
        dest: "/etc/php-fpm.d/www.conf"
        content: |
          [www]
          user = apache
          group = apache
          listen = /run/php-fpm/www.sock
          listen.acl_users = apache,nginx
          listen.allowed_clients = 127.0.0.1
          listen.mode = 0666
          pm = dynamic
          pm.max_children = 250
          pm.start_servers = 50
          pm.min_spare_servers = 50
          pm.max_spare_servers = 150
          pm.max_requests = 500
          pm.status_path = /status
          slowlog = /var/log/php-fpm/www-slow.log
          request_terminate_timeout = 1800
          clear_env = yes
          php_admin_value[error_log] = /var/log/php-fpm/www-error.log
          php_admin_flag[log_errors] = on
          php_value[session.save_handler] = files
          php_value[session.save_path]    = /var/lib/php/session
          php_value[soap.wsdl_cache_dir]  = /var/lib/php/wsdlcache
