---
- name: git checkout code and install
  hosts: localhost
  gather_facts: no
  become: true
  vars:
    system_repo_url: git@github.com:twidpay-global/twid_system.git
    api_repo_url: git@github.com:twidpay-global/twid_api.git
    tasks_repo_url: git@github.com:twidpay-global/twid_tasks.git
    merchant_repo_url: git@github.com:twidpay-global/twid_merchant.git
    mapi_repo_url: git@github.com:twidpay-global/twid_mapi.git
    tpap_repo_url: git@github.com:twidpay-global/twid_tpap.git
    system_dest_dir: /twid/system
    api_dest_dir: /twid/api
    tasks_dest_dir: /twid/tasks
    merchant_dest_dir: /twid/merchant
    mapi_dest_dir: /twid/mapi
    tpap_dest_dir: /twid/tpap
    branch: beta
    secret_id: twid/git_ssh_key
    ssh_private_key_path: /home/rocky/.ssh/id_rsa
    region: ap-south-2
  tasks:        
    - name: Install botocore and boto3
      shell: |
        sudo yum -y install wget
        sudo wget https://bootstrap.pypa.io/get-pip.py -O /tmp/get-pip.py
        sudo python3 /tmp/get-pip.py
        sudo pip3 install botocore boto3 || sudo /usr/local/bin/pip3 install botocore boto3
    
    - name: adding python script to fetch secrets
      copy:
        dest: /etc/ansible/fetch_ssh_key.py
        content: |
          #!/usr/bin/env python3
          import boto3
          import base64
          import json
          import sys
          
          # Fetch arguments from Ansible playbook
          secret_id = sys.argv[1]
          ssh_private_key_path = sys.argv[2]  # File path to store the encoded private key
          region = sys.argv[3]
          
          # Create a Secrets Manager client
          client = boto3.client('secretsmanager', region_name=region)

          # Fetch the secret value from AWS Secrets Manager
          response = client.get_secret_value(SecretId=secret_id)

          # Decode the base64 secret
          secret = json.loads(response['SecretString'])

          # Log the secret content for debugging
          print("Secret content:", secret)

          # Fetch the correct key from the secret
          if 'ssh_key' in secret:
              private_key = secret['ssh_key']
          else:
              print("The key 'ssh_key' was not found in the secret.")
              sys.exit(1)

          # Decode the base64 private key
          decoded_key = base64.b64decode(private_key)

          # Store the decoded private key into a file
          with open(ssh_private_key_path, "wb") as decoded_file:
              decoded_file.write(decoded_key)
              
    - name: update permisssions for python file
      shell: |
        sudo chmod 777 /etc/ansible/fetch_ssh_key.py
        
    - name: Fetch SSH private key from AWS Secrets Manager using boto3
      command: /etc/ansible/fetch_ssh_key.py "{{ secret_id }}" "{{ ssh_private_key_path }}" "{{ region }}"
      register: secret
      
    - name: update permissions for private keys
      shell: |
        sudo chown rocky:rocky /home/rocky/.ssh/id_rsa
        sudo chmod 600 /home/rocky/.ssh/id_rsa
        sudo chmod 777 /twid
        
    - name: Clone the Git System repository
      git:
        repo: "{{ system_repo_url }}"
        dest: "{{ system_dest_dir }}"
        version: "{{ branch }}"
        key_file: "{{ ssh_private_key_path }}"
        update: no
      environment:
        GIT_SSH_COMMAND: ssh -i {{ ssh_private_key_path }} -o StrictHostKeyChecking=no

    - name: Clone the Git Api repository
      git:
        repo: "{{ api_repo_url }}"
        dest: "{{ api_dest_dir }}"
        version: "{{ branch }}"
        key_file: "{{ ssh_private_key_path }}"
        update: no
      environment:
        GIT_SSH_COMMAND: ssh -i {{ ssh_private_key_path }} -o StrictHostKeyChecking=no

    - name: Clone the Git Tasks repository
      git:
        repo: "{{ tasks_repo_url }}"
        dest: "{{ tasks_dest_dir }}"
        version: "{{ branch }}"
        key_file: "{{ ssh_private_key_path }}"
        update: no
      environment:
        GIT_SSH_COMMAND: ssh -i {{ ssh_private_key_path }} -o StrictHostKeyChecking=no

    - name: Clone the Git Merchant repository
      git:
        repo: "{{ merchant_repo_url }}"
        dest: "{{ merchant_dest_dir }}"
        version: "{{ branch }}"
        key_file: "{{ ssh_private_key_path }}"
        update: no
      environment:
        GIT_SSH_COMMAND: ssh -i {{ ssh_private_key_path }} -o StrictHostKeyChecking=no

    - name: Clone the Git Mapi repository
      git:
        repo: "{{ mapi_repo_url }}"
        dest: "{{ mapi_dest_dir }}"
        version: "{{ branch }}"
        key_file: "{{ ssh_private_key_path }}"
        update: no
      environment:
        GIT_SSH_COMMAND: ssh -i {{ ssh_private_key_path }} -o StrictHostKeyChecking=no

    - name: Clone the Git Tpap repository
      git:
        repo: "{{ tpap_repo_url }}"
        dest: "{{ tpap_dest_dir }}"
        version: "{{ branch }}"
        key_file: "{{ ssh_private_key_path }}"
        update: no
      environment:
        GIT_SSH_COMMAND: ssh -i {{ ssh_private_key_path }} -o StrictHostKeyChecking=no

    - name: Clone the Git Tasks_tpap repository
      git:
        repo: "{{ tasks_tpap_repo_url }}"
        dest: "{{ tasks_tpap_dest_dir }}"
        version: "{{ branch }}"
        key_file: "{{ ssh_private_key_path }}"
        update: no
      environment:
        GIT_SSH_COMMAND: ssh -i {{ ssh_private_key_path }} -o StrictHostKeyChecking=no

    - name: Clean up SSH private key file
      file:
        path: "{{ ssh_private_key_path }}"
        state: absent

    - name: Create directory
      shell: |
        sudo mkdir /twid/system/storage/framework
        sudo mkdir /twid/system/storage/framework/cache
        sudo mkdir /twid/system/storage/framework/sessions
        sudo mkdir /twid/system/storage/framework/views

    - name: system_install_composer script
      copy:
        dest: "/tmp/system_install_composer.sh"
        content: |
          #!/bin/bash
          sudo chmod -R 775 /twid/system/
          sudo chown -R apache:kushal /twid/system/
          git config --global --add safe.directory /twid/system
          cd /twid/system
          sudo -u kushal -- composer update --no-dev
          sudo -u kushal -- composer install --no-dev -n
        
    - name: run system_install_composer script
      shell: |
        sudo chmod +x /tmp/system_install_composer.sh
        sudo bash /tmp/system_install_composer.sh
        sudo rm -f /tmp/system_install_composer.sh

    - name: api_install_composer script
      copy:
        dest: "/tmp/api_install_composer.sh"
        content: |
          #!/bin/bash
          sudo chmod -R 775 /twid/api/
          sudo chown -R apache:kushal /twid/api/
          git config --global --add safe.directory /twid/api
          cd /twid/api
          sudo -u kushal -- composer update --no-dev
          sudo -u kushal -- composer install --no-dev -n
        
    - name: run api_install_composer script
      shell: |
        sudo chmod +x /tmp/api_install_composer.sh
        sudo bash /tmp/api_install_composer.sh
        sudo rm -f /tmp/api_install_composer.sh

    - name: tasks_install_composer script
      copy:
        dest: "/tmp/tasks_install_composer.sh"
        content: |
          #!/bin/bash
          sudo chmod -R 775 /twid/tasks/
          sudo chown -R apache:kushal /twid/tasks/
          git config --global --add safe.directory /twid/tasks
          cd /twid/tasks
          sudo -u kushal -- composer update --no-dev
          sudo -u kushal -- composer install --no-dev -n
        
    - name: run tasks_install_composer script
      shell: |
        sudo chmod +x /tmp/tasks_install_composer.sh
        sudo bash /tmp/tasks_install_composer.sh
        sudo rm -f /tmp/tasks_install_composer.sh

    - name: merchant_install_composer script
      copy:
        dest: "/tmp/merchant_install_composer.sh"
        content: |
          #!/bin/bash
          sudo chmod -R 775 /twid/merchant/
          sudo chown -R apache:kushal /twid/merchant/
          git config --global --add safe.directory /twid/merchant
          cd /twid/merchant
          sudo -u kushal -- composer update --no-dev
          sudo -u kushal -- composer install --no-dev -n
        
    - name: run merchant_install_composer script
      shell: |
        sudo chmod +x /tmp/merchant_install_composer.sh
        sudo bash /tmp/merchant_install_composer.sh
        sudo rm -f /tmp/merchant_install_composer.sh

    - name: mapi_install_composer script
      copy:
        dest: "/tmp/mapi_install_composer.sh"
        content: |
          #!/bin/bash
          sudo chmod -R 775 /twid/mapi/
          sudo chown -R apache:kushal /twid/mapi/
          git config --global --add safe.directory /twid/mapi
          cd /twid/mapi
          sudo -u kushal -- composer update --no-dev
          sudo -u kushal -- composer install --no-dev -n
        
    - name: run mapi_install_composer script
      shell: |
        sudo chmod +x /tmp/mapi_install_composer.sh
        sudo bash /tmp/mapi_install_composer.sh
        sudo rm -f /tmp/mapi_install_composer.sh

    - name: tpap_install_composer script
      copy:
        dest: "/tmp/tpap_install_composer.sh"
        content: |
          #!/bin/bash
          sudo chmod -R 775 /twid/tpap/
          sudo chown -R apache:kushal /twid/tpap/
          git config --global --add safe.directory /twid/tpap
          cd /twid/tpap
          sudo -u kushal -- composer update --no-dev
          sudo -u kushal -- composer install --no-dev -n
        
    - name: run tpap_install_composer script
      shell: |
        sudo chmod +x /tmp/tpap_install_composer.sh
        sudo bash /tmp/tpap_install_composer.sh
        sudo rm -f /tmp/tpap_install_composer.sh

    - name: tasks_tpap_install_composer script
      copy:
        dest: "/tmp/tasks_tpap_install_composer.sh"
        content: |
          #!/bin/bash
          sudo chmod -R 775 /twid/tasks_tpap/
          sudo chown -R apache:kushal /twid/tasks_tpap/
          git config --global --add safe.directory /tasks_twid/tpap
          cd /twid/tasks_tpap
          sudo -u kushal -- composer update --no-dev
          sudo -u kushal -- composer install --no-dev -n
        
    - name: run tasks_tpap_install_composer script
      shell: |
        sudo chmod +x /tmp/tasks_tpap_install_composer.sh
        sudo bash /tmp/tasks_tpap_install_composer.sh
        sudo rm -f /tmp/tasks_tpap_install_composer.sh
        
    - name: update directory permision
      shell: |
        sudo chown -R apache:kushal /twid/system/
        sudo chown -R apache:kushal /twid/api/
        sudo chown -R apache:kushal /twid/tasks/
        sudo chown -R apache:kushal /twid/merchant/
        sudo chown -R apache:kushal /twid/mapi/
        sudo chown -R apache:kushal /twid/tpap/
        sudo chown -R apache:kushal /twid/tasks_tpap/
        sudo chmod 755 /twid
          
    # - name: Wait for 10 minutes
    #   ansible.builtin.pause:
    #     minutes: 10
