---
- name: install efs_utils
  hosts: localhost
  gather_facts: no
  become: true
  tasks:
    - name: Install required packages for building EFS utils
      dnf:
        name:
          - git
          - rpm-build
          - make
          - rust
          - cargo
          - openssl-devel
        state: present

    - name: Install botocore and boto3
      shell: |
        sudo yum -y install wget
        sudo wget https://bootstrap.pypa.io/get-pip.py -O /tmp/get-pip.py
        sudo python3 /tmp/get-pip.py
        sudo pip3 install botocore boto3 || sudo /usr/local/bin/pip3 install botocore boto3
