---
- name: install PHP 8.2
  hosts: localhost
  gather_facts: no
  become: true
  become_user: root
  become_method: sudo
  tasks:

    - name: Ensure EPEL repository is installed
      dnf:
        name: epel-release
        state: present

    - name: Import Remi GPG key
      rpm_key:
        state: present
        key: https://rpms.remirepo.net/RPM-GPG-KEY-remi          

#    - name: Install Remi repository for PHP 8.2
#      dnf:
#        name: http://rpms.remirepo.net/enterprise/remi-release-9.rpm
#        state: present

    - name: Install Remi repository for PHP 8.2 manually
      shell: |
        dnf install -y http://rpms.remirepo.net/enterprise/remi-release-9.rpm

    - name: Install DNF utilities (for enabling the Remi repository)
      dnf:
        name: dnf-utils
        state: present

    - name: Disable all PHP modules
      command: dnf module disable php -y
      become: true

    - name: Enable Remi PHP 8.2 repository
      command: dnf module enable php:remi-8.2 -y
      become: true

    - name: Install PHP 8.2 and common extensions
      dnf:
        name:
          - php
          - php-bcmath
          - php-cli
          - php-common
          - php-devel
          - php-fpm
          - php-gd
          - php-intl
          - php-mbstring
          - php-mysqlnd
          - php-opcache
          - php-pdo
          - php-process
          - php-soap
          - php-xml
          - php-zip
          - php-pear           
          - php-igbinary       
          - php-redis         
          - php-apcu
        state: present
