---
- name: Install Composer and PHP extensions
  hosts: localhost
  gather_facts: no
  become: true
  tasks:

    - name: Download Composer installer to /tmp
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-setup.php
        mode: '0644'

    - name: Install Composer
      shell: |
        cd /tmp
        php composer-setup.php --install-dir=/bin --filename=composer
      args:
        creates: /bin/composer  # Skip if Composer is already installed

    - name: Clean up Composer installer
      file:
        path: /tmp/composer-setup.php
        state: absent

    - name: Install redis extension via PECL
      command: pecl install redis
#      creates: /usr/lib/php/modules/redis.so  # Only install if the extension isn't already present

    - name: Install APCu extension via PECL
      command: pecl install apcu
#      creates: /usr/lib/php/modules/apcu.so  # Only install if the extension isn't already present

#    - name: Install igbinary extension via PECL
#      command: pecl install igbinary
#      creates: /usr/lib/php/modules/igbinary.so  # Only install if the extension isn't already present
