---
- name: Install Tripwire
  hosts: localhost
  become: yes
  gather_facts: no
  tasks:

    - name: Ensure the EPEL repository is installed
      dnf:
        name: epel-release
        state: present

    - name: Install Tripwire package
      dnf:
        name: tripwire
        state: present

    - name: Generate Tripwire key files using the default setup
      command: tripwire-setup-keyfiles  # No need for sudo because of become: yes
      register: tripwire_setup
      failed_when: "'Error' in tripwire_setup.stderr"  # Prevent playbook from failing on minor errors
      changed_when: false

    - name: Generate Tripwire key files (first time setup)
      command: tripwire --init  # No need for sudo because of become: yes
      register: tripwire_init
      failed_when: "'Error' in tripwire_init.stderr"  # Prevent playbook from failing on minor errors

    - name: Set the correct permissions for Tripwire configuration files
      file:
        path: "{{ item }}"
        owner: root
        group: root
        mode: '0644'
      with_items:
        - /etc/tripwire/tw.cfg
        - /etc/tripwire/tw.pol

    - name: Check Tripwire database integrity
      command: tripwire --check
      register: tripwire_check
      failed_when: "'Error' in tripwire_check.stderr"
      changed_when: false
