---
- name: Create nodeexporter user
  hosts: localhost
  gather_facts: no
  become: true

  tasks:
    - name: Create the nodeexporter user
      user:
        name: nodeexporter
        comment: "User for running exporters"
        create_home: no  
        shell: /sbin/nologin  
        state: present   
        
    - name: Create the kushal user
      user:
        name: kushal
        create_home: yes
        shell: /bin/bash
        state: present
    - name: updating .bash_profile
      lineinfile:
        path: "/home/kushal/.bash_profile"
        line: 'export PATH=$PATH:$HOME/.local/bin:$HOME/bin'
        
    - name: Creating .ssh directory
      command: sudo mkdir /home/kushal/.ssh

    - name: Updating kushal's ssh keys
      copy:
        dest: "/home/kushal/.ssh/authorized_keys"
        content: |
          ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZYJSrjCvnxLTuHDY164cKJ5i9qOAQEGkQ5lDjEvS5y1WRiu76ptmo2XJj3ktkJXMXjdulMc0nUKvf0cVtFZcwA7RBkGgN+/1TEFoSejctYKznX2I5KUgFN32+S/6wWm1bQ7Xak0lpWsS8BS0MCmaQG4Ex90aDkAUb2Q4yF7vxsl6Dlu0kQCOMas9tw4UGTb6WuG0yFwJas9aFR+6sp32fFXL8Re6rYwV9FWqHPt1nKjYmyRg3+7KxHSDwm9N1wJmxGUNo22LlQB/jXnrDIhYWwMPW6Y5EFFN89oecwOyQGOmOdDvSGHEF4QxZ5WBlBsV0MrmJ1StWbqxpVKiRtP/P kushal@bastion

    - name: Updating kushal's keys permissions  
      file:
        path: "/home/kushal/.ssh/authorized_keys"
        owner: "kushal"
        group: "kushal"
        mode: '0600'
        
    - name: Create the john.zacharia user
      user:
        name: john.zacharia
        create_home: yes
        shell: /bin/bash
        state: present
        
    - name: updating .bash_profile
      lineinfile:
        path: "/home/john.zacharia/.bash_profile"
        line: 'export PATH=$PATH:$HOME/.local/bin:$HOME/bin'
        
    - name: Creating .ssh directory
      command: sudo mkdir /home/john.zacharia/.ssh

    - name: Updating john.zacharia's ssh keys
      copy:
        dest: "/home/john.zacharia/.ssh/authorized_keys"
        content: |
          ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDRQp+DB50vHjswXV9CrixF3cvDy7XR1o4e8jFwkuFtnuk4A4R+QygTsxdTITSU0tlpRjVlTo7rp6MvHth/Mjrr2EJxsN6gw6JwYiSH6jqpn9VjIpgpwES+7yr8fE6m/PCGjAkbUt78ZFECU08UofR831qFF1dIL3S74EuyhX3lI47AR/RbaXNr33fgFp868NWWyz1755E05e+lXl2B28tsnTh+EVQRpLIC9IGhq1HKW5SwCxtCEnoJ8OjdUAVJfwr7I/SwZAXdUgOODvhjUKrbWuyigdmkgJM5K+p2sd4gKFp2Ad4hPIRPfmLd8s2K7/ZXKu6XNXXzfTJluIWZNIEr john.zacharia@elk.twidpay.com
    
    - name: Updating john.zacharia's keys permissions  
      file:
        path: "/home/john.zacharia/.ssh/authorized_keys"
        owner: "john.zacharia"
        group: "john.zacharia"
        mode: '0600'

    - name: Create the avinash user
      user:
        name: avinash
        create_home: yes
        shell: /bin/bash
        state: present

    - name: updating .bash_profile
      lineinfile:
        path: "/home/avinash/.bash_profile"
        line: 'export PATH=$PATH:$HOME/.local/bin:$HOME/bin'
    
    - name: Creating .ssh directory
      command: sudo mkdir /home/avinash/.ssh

    - name: Updating avinash's ssh keys
      copy:
        dest: "/home/avinash/.ssh/authorized_keys"
        content: |
          ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1mEdtCETpMm+PE2i3daGyKMD6i5Cx2xZYvnMLCM5Ih9eM39t76wE/rb3PSjk+ZUJMML0r8//7aIb+ooR9960olhI9PuYD9sa4LGn8ZrKXa/oSbRRqlO/+4ifSHM7OVUUlpJjNp5gWCSExKEEaTSp0/SvD07VoO/Hskb4MLrOvu4Uo0PlDk5CSRrFqXMnTKP8TY39uCS5Un17b2qQ18viugg6eJ/5vpBqvJmrF5rj+4DIb6afpd9lxaj9cOBtdsYinDH6ZMAv+FUTgCup3gacts3/ezKl/DYtvxaSaftp9nCufkCMJMb4zlfKXsFeZsrtaZsuEDoohYtPzopUQ3QcF avinash@bastion
    
    - name: Updating avinash's keys permissions  
      file:
        path: "/home/avinash/.ssh/authorized_keys"
        owner: "avinash"
        group: "avinash"
        mode: '0600'

    - name: Create the bharath user
      user:
        name: bharath.tg
        create_home: yes
        shell: /bin/bash
        state: present

    - name: updating .bash_profile
      lineinfile:
        path: "/home/bharath.tg/.bash_profile"
        line: 'export PATH=$PATH:$HOME/.local/bin:$HOME/bin'
    
    - name: Creating .ssh directory
      command: sudo mkdir /home/bharath.tg/.ssh

    - name: Updating bharath's ssh keys
      copy:
        dest: "/home/bharath.tg/.ssh/authorized_keys"
        content: |
          ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6pIGmULlYylASbUjHagfOyfPBlrwiNcurqs5o4W7QXvB4MTpxjNLPI2l793B2bMKLwu3cBstdNyZKh7g6JXXvWF+rKYyAkwTkDLraOXMLq/6yD340LErb4tN+MAeVzY+M8akb+B6VAAL9j/8jrXFdhAaTl4Rr7u6G0bwt74AF0k9tAHmnc54DDVV7kjBH/ZcvT4yHA7I7Wp8OSP8wBJq0OmGPSjd/0bVGKIBRXUgc0ZDzIN4vlvKrCCKoMAyVh1uvF2TuQ/1EQVPj+dOdJuOcrVGDlSOwxFHrlM2ui9Av8IxVcnG78IRxnlv/xaAuqhfiuE0CRhRpRJSq5LWLsPuX bharath.tg@ip-172-31-24-172.ap-south-1.compute.internal
    
    - name: Updating bharath's keys permissions  
      file:
        path: "/home/bharath.tg/.ssh/authorized_keys"
        owner: "bharath.tg"
        group: "bharath.tg"
        mode: '0600'

    - name: updating .bash_profile
      lineinfile:
        path: "/home/rocky/.bash_profile"
        line: 'export PATH=$PATH:$HOME/.local/bin:$HOME/bin'

    - name: Updating rocky's ssh keys
      copy:
        dest: "/home/rocky/.ssh/id_rsa"
        content: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIEpAIBAAKCAQEAubLLNopGbCmxjusOEISHeBOzXhgLlGfJjgU999bvb5BthtRz
          TTQrDMGcOayolzgiSDrL389iMVR+Y9KhXA+MV9TKh/+GVALBbvZ0Qr9o1JQLbhwx
          316kk1xMw/Rxl7GKc2v0x8e7Kh6K5iFr0X0Mas4Rlb0I4r/Ttd9m95c+CCdBN1GI
          akzWcyNP68wokVVqvQ9iNblh2n4mJQ7txAUQuZeU0h9yowN3T2edsbaqT/V99M3+
          GhW/47KrgpLe1BCd8dEVztsLVAn2y5xvuws0q+CQqNYD0yjzOMyVH67IbA75HUrD
          eHHqIrf1UOLKh6BTL0MvnzQQoGAjCC2uqwizkQIDAQABAoIBAQCyoynUBL7sLEuv
          5bT49NTxEVqaaN0y3YjKQ4ayVaSuGS0T6Gom2cmUEug7nznrhseL3mvjmLeoJtUT
          KDuruRVUJNLUc16AkMoN+a4ry8CHxwcb3KmpbH07eS4rz4o62EMM98xZJ22Ifis2
          aO40b2wzjpriBiB3KPv72LZP9cFpyt3EXw3b5V+LL9Dd4sXtD5bjwmNd61aI9iga
          h/ejKjd9E80LurStkn6A1GvKDglh9QrBK5aEyTOYH/0jFx94SHHDdofJ1BTM6BRS
          Pr589I7zaX6pJYtUwvzPpWNhDZ8JzzEap0jzcoWIr9P5fulrJH/3guCKCofo8Y/p
          X+fg5neFAoGBAODO5B+/o34++XQ+PPNv/WAwcHknnJI8W+lex+v3qPVztmeSp4wy
          TQPCZJDrGmjQv+jCIBGjmcBIS4cj8aT1D2382M+aQlvh+f1jAOCqsRaKK7WdLl/P
          LvPj6SXzFnWjio9dOFm/N2g7C4S+z7DkQxI3ROORwgbfpOlFZLVmvlJbAoGBANN2
          vNVFfKK5vDa739waOkgFbBZmBHY8GJfd9mdSFn01jQAMHXT6ZPzLH37zGVMI3Z6P
          knimMHhMdm7lvaj80FSBtW+V4nnVZ79AYyFAHde4m8G/3wZ0iOyAA+DYOFB6qqj/
          qcwpV/eUf8APNuHm+TRVBaq2nyGUF2Kp2YYNZN2DAoGAdY+7/F5bQUntabyiYyvN
          dN/f8XulhVPLPN8z7VI2KSW53a/zrn0fiTe/H4nS5b1EnpPl8VN8s/EajjFdzMXa
          q8nuF6Kz0Rj7gmajrtmUghT/hpoMBk5yX1hwNEhLFnnPm+lD7qrwbrFx9JlUQ00b
          RgthGyC+Npn9w39mivaP0MECgYAxlWrruzJhWZnXX7A7BO9bieHxUpSDQM4ndgVb
          7rSVQWRBeZXCox/g4qQM+WWbwb1te47FuXouCwfOMxKIuFcFKbDobEXBeZetEaTs
          3ALjXUcwZBQgiFy+z7mZFDoILOstW11uINeelvRpjWe6CpWufq0ofU/M6NOe7+Kw
          ex2GjwKBgQCUMCz5781uV+0q7I0uVJpbSAf61DJqSYi2uN0O+zld26PiRqF/12yS
          46U3KqqzwZ2347rdbEej14DYEkfUjzWCgX1/lzU1zPgN9MPLlPh8HNk9yfmXSAmG
          6e8osBWnVNiELb8seGgo8Mm5iKC4XULtBkCH2Iu/VI6ylUOt/VYmkw==
          -----END RSA PRIVATE KEY-----
    
    - name: Updating rocky's ssh keys permissions  
      file:
        path: "/home/rocky/.ssh/id_rsa"
        owner: "rocky"
        group: "rocky"
        mode: '0600'

    - name: adding usrs to sudoers
      shell: |
        echo 'kushal	ALL=(ALL)	NOPASSWD: ALL' >> /etc/sudoers
        echo 'john.zacharia	ALL=(ALL)	NOPASSWD: ALL' >> /etc/sudoers
        echo 'avinash	ALL=(ALL)	NOPASSWD: ALL' >> /etc/sudoers
        echo 'bharath.tg	ALL=(ALL)	NOPASSWD: ALL' >> /etc/sudoers
