---
- name: update configuration files
  hosts: localhost
  gather_facts: no
  become: true

  tasks:
    - name: Create directory
      shell: |
        sudo mkdir /twid/log
        sudo mkdir /etc/nginx/snippets

    - name: updating configuration nginx.conf
      copy:
        dest: "/etc/nginx/nginx.conf"
        content: |


    - name: updating configuration conf.d/a.conf
      copy:
        dest: "/etc/nginx/conf.d/a.conf"
        content: |
          server {
            listen 80 default_server;
            server_name a.tasks.twidpay.com;
            include /etc/nginx/snippets/headers.conf;
            root /var/www/html/healthcheck;
            index index.php index.html index.htm;
            location / {
                        try_files $uri $uri/ /index.php?$args;
            }
            location ~ \.php$ {
            try_files $uri =404;
            fastcgi_pass unix:/run/php-fpm/www.sock;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
            }
          }

    - name: updating configuration conf.d/tasks.conf
      copy:
        dest: "/etc/nginx/conf.d/tasks.conf"
        content: |
          server {
            listen 80;
            server_name tasks.twidpay.com www.tasks.twidpay.com tasks.local.twidpay.com;
            include /etc/nginx/snippets/headers.conf;
            root /twid/tasks/public;
            access_log /twid/log/twid_tasks_access.log;
            error_log /twid/log/twid_tasks_error.log crit;
            index index.php index.html index.htm;
            proxy_read_timeout 1800s;
            proxy_connect_timeout 1800s;
            proxy_send_timeout 1800s;
            fastcgi_connect_timeout 1800s;
            fastcgi_read_timeout 1800s;
            fastcgi_send_timeout 1800s;
            fastcgi_keep_conn on;
            location / {
              try_files $uri $uri/ /index.php?$args;
            }
            location ~ \.php$ {
              try_files $uri =404;
              fastcgi_pass unix:/run/php-fpm/www.sock;
              fastcgi_index index.php;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              include fastcgi_params;

              # Hide PHP headers
              fastcgi_hide_header             X-Powered-By;
              fastcgi_hide_header             X-CF-Powered-By;
            }
            location /status {
              stub_status;
              allow 127.0.0.1;        #only allow requests from localhost
              deny all;               #deny all other hosts
            }
            location ~ /\. {
              deny  all;
            }
          }

    - name: updating configuration conf.d/system.conf
      copy:
        dest: "/etc/nginx/conf.d/system.conf"
        content: |
          server {
            listen 80;
            server_name system.twidpay.com www.system.twidpay.com system.local.twidpay.com;
            include /etc/nginx/snippets/headers.conf;
            root /twid/system/public;
            access_log /twid/log/twid_system_access.log;
            error_log /twid/log/twid_system_error.log warn;
            index index.php index.html index.htm;
            proxy_read_timeout 1800s;
            proxy_connect_timeout 1800s;
            proxy_send_timeout 1800s;
            fastcgi_connect_timeout 1800s;
            fastcgi_read_timeout 1800s;
            fastcgi_send_timeout 1800s;
            fastcgi_keep_conn on;
            location / {
              try_files $uri $uri/ /index.php?$args;
            }
            location ~ \.php$ {
              try_files $uri =404;
              fastcgi_pass unix:/run/php-fpm/www.sock;
              fastcgi_index index.php;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              include fastcgi_params;
              # Hide PHP headers
              fastcgi_hide_header             X-Powered-By;
              fastcgi_hide_header             X-CF-Powered-By;
            }
            location /status {
              stub_status;
              allow 127.0.0.1;        #only allow requests from localhost
              deny all;               #deny all other hosts
            }
            location ~ /\. {
              deny  all;
            }
          }

    - name: updating configuration conf.d/security.conf
      copy:
        dest: "/etc/nginx/conf.d/security.conf"
        content: |
          server_tokens off;
          #add_header X-Frame-Options SAMEORIGIN;
          add_header X-Frame-Options DENY;
          add_header X-XSS-Protection "1; mode=block";
          #add_header X-Content-Type-Options nosniff;
          add_header Content-Security-Policy "default-src 'self' *.google.com *.amazon.com;";
          add_header Set-Cookie "Path=/; HttpOnly; Secure";
          add_header Referrer-Policy 'origin';

    - name: updating configuration snippets/headers.conf
      copy:
        dest: "/etc/nginx/snippets/headers.conf"
        content: | 
          location ^~ /.well-known/acme-challenge/ {
            allow all;
            root /var/lib/letsencrypt/;
            default_type "text/plain";
            try_files $uri =404;
          }
          add_header X-Content-Type-Options nosniff;
          add_header Strict-Transport-Security "max-age=15768000; includeSubdomains; preload";
