---
- name: Install Supervisord
  hosts: localhost
  gather_facts: no
  become: yes
  tasks:

    - name: Ensure EPEL repository is installed
      dnf:
        name: epel-release
        state: present

    - name: Install Supervisor
      dnf:
        name: supervisor
        state: present

    - name: updating configuration supervisord.conf
      copy:
        dest: "/etc/supervisord.conf"
        content: |
          [supervisord]
          logfile_maxbytes=50MB        ; (max main logfile bytes b4 rotation;default 50MB)
          logfile_backups=10           ; (num of main logfile rotation backups;default 10)
          loglevel=info                ; (log level;default info; others: debug,warn,trace)
          pidfile=/tmp/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
          nodaemon=false               ; (start in foreground if true;default false)
          minfds=1024                  ; (min. avail startup file descriptors;default 1024)
          minprocs=200                 ; (min. avail process descriptors;default 200)
          user=kushal                  ; (default is current user, required if root)
          directory=/tmp               ; (default is not to cd during start)
          
          [rpcinterface:supervisor]
          supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
          
          [unix_http_server]
          file=/tmp/supervisor.sock
          chmod=0755 ; sockef file mode (default 0700)
          
          [inet_http_server]
          port=127.0.0.1:9005
          ;username=abc
          
          [supervisorctl]
          ;srevreurl=http://127.0.0.1:9001
          serverurl=unix:///tmp/supervisor.sock
          ;username=abc
          ;serverurl=unix:///var/run/supervisor.sock ; use a unix:// URL  for a unix socket
          
          [include]
          files = /etc/supervisord.d/*.conf
         
    - name: updating configuration supervisord config
      copy:
        dest: "/etc/supervisord.d/octane.conf"
        content: |
          [program:octane]
          command=/usr/bin/php /twid/api/artisan octane:start --server=swoole --host=0.0.0.0 --port=8000 --workers=8 --task-workers=4
          directory=/twid/api
          user=kushal
          autostart=true
          autorestart=true
          redirect_stderr=true
          stdout_logfile=/twid/api/storage/logs/octane.log
          stdout_logfile_maxbytes=50MB
          stdout_logfile_backups=10
          stopsignal=TERM
          stopwaitsecs=10
          startretries=3