---
- name: Run multiple playbooks from one main playbook
  hosts: localhost
  gather_facts: no
  become: true 
  tasks:
    - ansible.builtin.debug:
        msg: "Main Playbook"
    - name: Pause for 10 minutes
      ansible.builtin.pause:
          minutes: 10

- name: import user playbook
  ansible.builtin.import_playbook: user_playbook.yml

- name: import nginx playbook
  ansible.builtin.import_playbook: nginx_playbook.yml

- name: Import php playbook 
  ansible.builtin.import_playbook: php_playbook.yml

- name: Import node_exporter playbook 
  ansible.builtin.import_playbook: node_exporter_playbook.yml

- name: Import nginx_prometheus_exporter playbook 
  ansible.builtin.import_playbook: nginx_prometheus_exporter_playbook.yml
    
