---
- name: main playbook
  hosts: localhost
  tasks:
    - ansible.builtin.debug:
        msg: "Start Main Playbook"

- name: import user playbook
  ansible.builtin.import_playbook: user_playbook.yml

- name: import nginx playbook
  ansible.builtin.import_playbook: nginx_playbook.yml

- name: Import php playbook 
  ansible.builtin.import_playbook: php_playbook.yml

- name: Import node_exporter playbook 
  ansible.builtin.import_playbook: node_exporter_playbook.yml

- name: Import nginx_prometheus_exporter playbook 
  ansible.builtin.import_playbook: nginx_prometheus_exporter_playbook.yml

- name: Import filebeat playbook 
  ansible.builtin.import_playbook: filebeat_playbook.yml

- name: Import phpfpm prometheus exporter playbook 
  ansible.builtin.import_playbook: phpfpm_prometheus_exporter_playbook.yml
