---
- name: main playbook
  hosts: localhost
  tasks:
    - ansible.builtin.debug:
        msg: "Start Main Playbook"
    - name: Copy files from /tmp/playbook to /tmp/packer
      shell: |
        cp -r /tmp/playbook/* /tmp/packer-provisioner-ansible-local/{{ ansible_playbook_name }}/

- name: import user playbook
  ansible.builtin.import_playbook: /tmp/playbook/user_playbook.yml

- name: import nginx playbook
  ansible.builtin.import_playbook: /tmp/playbook/nginx_playbook.yml

- name: Import php playbook 
  ansible.builtin.import_playbook: /tmp/playbook/php_playbook.yml

- name: Import node_exporter playbook 
  ansible.builtin.import_playbook: /tmp/playbook/node_exporter_playbook.yml

- name: Import nginx_prometheus_exporter playbook 
  ansible.builtin.import_playbook: /tmp/playbook/nginx_prometheus_exporter_playbook.yml

- name: Import filebeat playbook 
  ansible.builtin.import_playbook: /tmp/playbook/filebeat_playbook.yml

- name: Import phpfpm prometheus exporter playbook 
  ansible.builtin.import_playbook: /tmp/playbook/phpfpm_prometheus_exporter_playbook.yml
