---
- name: install nginx
  hosts: localhost
  gather_facts: no
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: Update all packages
      dnf:
        name: '*'
        state: latest

    - name: Install EPEL repository
      dnf:
        name: epel-release
        state: present

    - name: Install NGINX
      dnf:
        name: nginx
        state: present

    - name: Start NGINX service
      systemd:
        name: nginx
        state: started
        enabled: yes
