---
- name: install PHP 8.2
  hosts: localhost
  become: true
  tasks:

    - name: Ensure EPEL repository is installed
      dnf:
        name: epel-release
        state: present

    - name: Install Remi repository for PHP 8.2
      dnf:
        name: https://rpms.remirepo.net/enterprise/remi-release-9.rpm
        state: present

    - name: Install DNF utilities (for enabling the Remi repository)
      dnf:
        name: dnf-utils
        state: present

    - name: Enable Remi PHP 8.2 repository
      command: dnf module enable php:remi-8.2 -y
      become: true

    - name: Install PHP 8.2 and common extensions
      dnf:
        name:
          - php
          - php-bcmath
          - php-cli
          - php-common
          - php-devel
          - php-fpm
          - php-gd
          - php-intl
          - php-mbstring
          - php-mysqlnd
          - php-opcache
          - php-pdo
          - php-process
          - php-soap
          - php-xml
        state: present
