---
- name: update configuration files
  hosts: localhost
  gather_facts: no
  become: true
  become_user: root
  become_method: sudo

  tasks:
    - name: updating configuration selinux config
        copy:
          dest: "/etc/selinux/config"
          content: |
            SELINUX=permissive
            SELINUX=disabled
            
    - name: updating configuration nginx.conf
        copy:
          dest: "/etc/nginx/nginx.conf"
          content: |
            user nginx;
            worker_processes auto;
            error_log /var/log/nginx/error.log;
            pid /run/nginx.pid;

            include /usr/share/nginx/modules/*.conf;

            events {
                worker_connections 1024;
            }

            http {
                log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                                  '$status $body_bytes_sent "$http_referer" '
                                  '"$http_user_agent" "$http_x_forwarded_for"';

                access_log  /var/log/nginx/access.log  main;

                sendfile            		on;
                tcp_nopush          		on;
                tcp_nodelay         		on;
                client_header_timeout               60m;
                client_body_timeout                 60m;
                client_header_buffer_size           2k;
                client_body_buffer_size             256k;
                client_max_body_size                256m;
                large_client_header_buffers         4   8k;
                send_timeout                        600;
                keepalive_timeout                   600;
                keepalive_requests                  100000;
                reset_timedout_connection           on;
                server_name_in_redirect             off;
                server_names_hash_max_size          512;
                server_names_hash_bucket_size       512;
                types_hash_max_size 4096;

                include             /etc/nginx/mime.types;
                default_type        application/octet-stream;

                include /etc/nginx/conf.d/*.conf;

                server {
                    listen       80;
                    listen       [::]:80;
                    server_name  _;
                    root         /usr/share/nginx/html;

                    include /etc/nginx/default.d/*.conf;

              location / {
                    }

                    error_page 404 /404.html;
                    location = /404.html {
                    }

                    error_page 500 502 503 504 /50x.html;
                    location = /50x.html {
                    }
                }
            }
              
    - name: updating configuration filebeat.yml
          copy:
            dest: "/etc/filebeat/filebeat.yml"
            content: |
              filebeat.inputs:
              - type: filestream

                id: my-filestream-id

                enabled: true

                paths:
                  - /twid/system/storage/logs/exception_log
                  - /twid/system/storage/logs/access_log
                  - /twid/system/storage/logs/error_log
                  - /opt/codedeploy-agent/deployment-root/deployment-logs/*
                  - /twid/system/storage/logs/inbound.log
                  - /twid/system/storage/logs/outbound.log
                  - /twid/system/storage/logs/alert.log
                  - /twid/system/storage/logs/error.log
                  - /twid/system/storage/logs/critical.log
                  - /twid/system/storage/logs/info.log
                ignore_inactive: since_last_start

              filebeat.config.modules:
                path: ${path.config}/modules.d/*.yml

                reload.enabled: false

              setup.template.settings:
                index.number_of_shards: 1

              setup.kibana:

              output.logstash:
                hosts: ["10.210.41.164:5044"]

              processors:
                - add_host_metadata:
                    when.not.contains.tags: forwarded
                - add_cloud_metadata: ~
                - add_docker_metadata: ~
                - add_kubernetes_metadata: ~

    - name: Restart NGINX to apply configuration
      systemd:
        name: nginx
        state: reloaded

    - name: Restart Filebeat to apply configuration
      systemd:
        name: filebeat
        state: restarted
