---
- name: Create nodeexporter user
  hosts: localhost
  become: true  

  tasks:
    - name: Create the nodeexporter user
      user:
        name: nodeexporter
        comment: "User for running exporters"
        create_home: no  
        shell: /sbin/nologin  
        state: present   
