---
- name: Create nodeexporter user
  hosts: localhost
  become: true  

  tasks:
    - name: Disable SELinux enforcement
      command: setenforce 0
      ignore_errors: true  # Optional: Ignore errors if SELinux is not installed or not enforceable
      
    - name: Create the nodeexporter user
      user:
        name: nodeexporter
        comment: "User for running exporters"
        create_home: no  
        shell: /sbin/nologin  
        state: present   
