---
- name: Create nodeexporter user
  hosts: localhost
  gather_facts: no
  become: true
  become_user: root
  become_method: sudo 

  tasks:
    - name: Create the nodeexporter user
      user:
        name: nodeexporter
        comment: "User for running exporters"
        create_home: no  
        shell: /sbin/nologin  
        state: present   
